% -------------------------------------------------------------------
%  Generated by MATLAB on 7-May-2023 17:42:29
%  MATLAB version: 9.13.0.2049777 (R2022b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

out = saveVarsMat.out; % <1x1 Simulink.SimulationOutput> unsupported class

clear saveVarsMat;
