function code_mau2(X1, Y1)
%CREATEFIGURE(X1, Y1)
 % X1:  vector of plot x data
 % Y1:  vector of plot y data

%  Auto-generated by MATLAB on 03-May-2023 21:37:52

% Create figure
% figure1 = figure;

% Create axes
%axes1 = axes('X1',figure);
%hold(axes1,'on');
%axes2 = axes('Y1',figure);
%hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','FinalResult');

% Create ylabel
ylabel('Total Resistane Torque');

% Create xlabel
xlabel('Time (seconds)');

% Create title
title('Time Series Plot: Total Resistance Torque');

box(axes1,'on');
hold(axes1,'off');

box(axes2,'on');
hold(axes2,'off');
% Create legend
legend(axes1,'Final Result');

