function test2(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 03-May-2023 21:14:23

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot(X1,Y1,'Parent',axes1);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 10]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[140 280]);
grid(axes1,'on');
hold(axes1,'off');
